# calc_config.yml for calculator.rb messages

en:
  welcome: 
    "Welcome to Calculator! Enter your name:"
  valid_name: "Make sure to enter a valid name."
  first_number: "What's the first number?"
  valid_num: "Hmm.... that doesn't look like a valid number?"
  second_number: "What's the second number?"
  operator_prompt:  |
    What operation would you like to perform?
    1) add
    2) subtract
    3) multiply
    4) divide
  go_again: "Do you want to perform another calculation? (Y to calculate again)"
  goodbye: "Thank you for using the calculator. Goodbye!"
  valid_op: "Must choose 1, 2, 3, or 4"
