# calc_config.yml for calculator.rb messages

en:
  welcome: 
    "Welcome to Calculator! Enter your name:"
  valid_name: "Make sure to enter a valid name."
  first_number: "What's the first number?"
  valid_num: "Hmm.... that doesn't look like a valid number?"
  second_number: "What's the second number?"
  operator_prompt:  |
    What operation would you like to perform?
    1) add
    2) subtract
    3) multiply
    4) divide
  go_again: "Do you want to perform another calculation? (Y to calculate again)"
  goodbye: "Thank you for using the calculator. Goodbye!"
  valid_op: "Must choose 1, 2, 3, or 4"

es:
  welcome: "¡Bienvenido a Calculadora! Ingrese su nombre:"
  valid_name: "Asegúrese de ingresar un nombre válido"
  first_number: "¿Cuál es el primer número?"
  valid_num: "Hmm.... ¿Eso no parece un número válido?"
  second_number: "¿Cuál es el segundo número?"

  operator_prompt:  |
    ¿Qué operación le gustaría realizar?
     1) agregar
     2) restar
     3) multiplicar
     4) dividir
    
  go_again: "¿Quieres hacer otro cálculo? (Y volver a calcular)"
  goodbye: "Gracias por usar la calculadora. ¡Adiós!"
  valid_op: "Debe elegir 1, 2, 3 o 4"